"""add_test_data

Revision ID: 32a3b6e693d7
Revises: 67ef29c202fe
Create Date: 2021-11-18 22:44:01.529748

"""
from datetime import datetime, timedelta

from alembic import op

# revision identifiers, used by Alembic.
from sqlalchemy import table, column, Integer, DateTime, String

revision = '32a3b6e693d7'
down_revision = '67ef29c202fe'
branch_labels = None
depends_on = None

patient_table = table('patient',
                      column('id', Integer),
                      column('date_of_birth', DateTime),
                      column('created_at', DateTime),
                      column('created_at', DateTime),
                      )

diagnose_table = table('diagnose',
                       column('id', Integer),
                       column('diagnose_name', Integer),
                       )

association_table = table('patient_diagnose_association',
                          column('patient_id', Integer),
                          column('diagnose_id', Integer),
                          )


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.bulk_insert(patient_table,
                   [{"id": 1, "date_of_birth": datetime.now(), "created_at": datetime.now()},
                    {"id": 2, "date_of_birth": datetime.now() + timedelta(days=1),
                     "created_at": datetime.now() + timedelta(days=1)},
                    {"id": 3, "date_of_birth": datetime.now() + timedelta(days=2),
                     "created_at": datetime.now() + timedelta(days=2)}]
                   )
    op.bulk_insert(diagnose_table,
                   [{"id": 1, "diagnose_name": "lupus"},
                    {"id": 2, "diagnose_name": "amyloidosis"},
                    {"id": 3, "diagnose_name": "MS"}
                    ]
                   )
    op.bulk_insert(association_table,
                   [{"patient_id": 1, "diagnose_id": 1},
                    {"patient_id": 1, "diagnose_id": 2},
                    {"patient_id": 2, "diagnose_id": 2},
                    {"patient_id": 2, "diagnose_id": 3},
                    {"patient_id": 3, "diagnose_id": 3},
                    ]
                   )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
