"""patient_diagnose_tables

Revision ID: 67ef29c202fe
Revises: 
Create Date: 2021-11-18 22:42:39.447148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67ef29c202fe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diagnose',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('diagnose_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patient',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date_of_birth', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patient_diagnose_association',
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('diagnose_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['diagnose_id'], ['diagnose.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('patient_id', 'diagnose_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patient_diagnose_association')
    op.drop_table('patient')
    op.drop_table('diagnose')
    # ### end Alembic commands ###
